# This is the project specific Settings.yml file.
# Place Sphinx specific build information here.
# Settings given here will replace the settings of 'conf.py'.

---
conf.py:
  copyright: 2009-2020
  project: Apache Tika for TYPO3
  version: 6.0.1
  release: 6.0.1
  latex_documents:
  - - Index
    - tika.tex
    - Apache Tika for TYPO3
    - Ingo Renner
    - Timo Hund
    - manual
  html_theme_options:
      github_repository: TYPO3-Solr/ext-tika
      github_branch: master
    latex_elements:
    papersize: a4paper
    pointsize: 10pt
    preamble: \usepackage{typo3}
  intersphinx_mapping:
    t3tsref:
    - http://docs.typo3.org/typo3cms/TyposcriptReference/
    - null
...
